create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=MyISAM;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=MyISAM;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=MyISAM;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=MyISAM;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=MyISAM;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=MyISAM;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=MyISAM;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=MyISAM;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=MyISAM;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=MyISAM;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=MyISAM;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=MyISAM;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=MyISAM;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=MyISAM;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=MyISAM;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=MyISAM;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=MyISAM;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=MyISAM;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=MyISAM;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=MyISAM;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=MyISAM;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=MyISAM;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=MyISAM;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=MyISAM;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=MyISAM;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=MyISAM;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=MyISAM;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=InnoDB;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=InnoDB;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=InnoDB;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=InnoDB;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=InnoDB;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=InnoDB;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=InnoDB;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=InnoDB;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=InnoDB;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=InnoDB;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=InnoDB;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=InnoDB;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=InnoDB;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=InnoDB;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=InnoDB;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=InnoDB;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=InnoDB;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=InnoDB;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=InnoDB;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=InnoDB;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=InnoDB;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=InnoDB;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=InnoDB;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=InnoDB;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=InnoDB;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=InnoDB;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=InnoDB;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=InnoDB;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table huan_luyen_vien (id varchar(255) not null auto_increment, dob datetime, age integer, name varchar(255), so_dien_thoai varchar(255), primary key (id)) engine=InnoDB;
create table huan_luyen_vien_teams (hlv_id varchar(255) not null, teams_id varchar(255) not null) engine=InnoDB;
create table match (id varchar(255) not null auto_increment, ngay_thi_dau datetime, thoi_gian_thi_dau varchar(255), tien_datcoc integer, team_id varchar(255), team_id1 varchar(255), trongtai_id varchar(255), primary key (id)) engine=InnoDB;
create table player (id varchar(255) not null auto_increment, chi_so_chuyen integer, chi_so_ky_thuat integer, chi_so_sut integer, so_ao integer, so_ban_thang integer, so_dien_thoai integer, avartar varchar(255), can_nang integer, chieu_cao integer, name varchar(255), pass_word varchar(255), user_name varchar(255), team_id varchar(255), primary key (id)) engine=InnoDB;
create table role (id bigint not null, name varchar(255), primary key (id)) engine=InnoDB;
create table san_thi_dau (id varchar(255) not null auto_increment, address varchar(255), avatar varchar(255), so_dien_thoai varchar(255), status bit, primary key (id)) engine=InnoDB;
create table team (id varchar(255) not null auto_increment, tran_hoa integer, tran_thua integer, tran_win integer, logo varchar(255), name varchar(255), so_dien_thoai varchar(255), captain_id varchar(255), hlv_id varchar(255), primary key (id)) engine=InnoDB;
create table trong_tai (id varchar(255) not null auto_increment, dob date, age integer, can_nang integer, chieu_cao integer, name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null, age integer not null, name varchar(255), pass_word varchar(255), primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, roles_id bigint not null) engine=InnoDB;
alter table huan_luyen_vien_teams add constraint UK_l58uusn9dsjvt702qvbyi5djl unique (teams_id);
alter table huan_luyen_vien_teams add constraint FKafgqn12ujlco32ut3wosf1a77 foreign key (teams_id) references team (id);
alter table huan_luyen_vien_teams add constraint FKhx8jomjj00di7352sxhd6qgsq foreign key (hlv_id) references huan_luyen_vien (id);
alter table match add constraint FK7oi14pd4sn24w1q63konp77cx foreign key (team_id) references team (id);
alter table match add constraint FKd5v0acw4x6b64hogbalqmyuns foreign key (team_id1) references team (id);
alter table match add constraint FK5a43n0qoxehie1p598j49wtnl foreign key (trongtai_id) references trong_tai (id);
alter table player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team (id);
alter table team add constraint FKqj6c0ygmcanmnc0ftusw5ecli foreign key (captain_id) references player (id);
alter table team add constraint FKqpynmplrtn81im1tp8vl7c9x6 foreign key (hlv_id) references huan_luyen_vien (id);
alter table user_roles add constraint FKj9553ass9uctjrmh0gkqsmv0d foreign key (roles_id) references role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);
